[test]
# test data
elements = [500, 1_000, 2_000, 5_000, 10_000, 25_000, 50_000]
max_values = [1000000]
skews = [0.0]
rs_scale= [2.0]
rs_join_columns = [1]
profile = false


# algorithm setup
# probe
probe_build_table_loads = [0.25, 0.5, 0.75, 1.0]
probe_build_n_per_threads = [1, 2, 4]
probe_build_threads = [128, 256, 512, 1024]
probe_prefix_n_per_threads = [1, 2, 4]
probe_prefix_threads = [128, 256, 512, 1024]
probe_extract_n_per_threads = [1, 2, 4]
probe_extract_threads = [128, 256, 512, 1024]
probe_extract_x_threads = [8, 16, 32, 64]
probe_modes = [0, 1, 2]

# launch
max_streams = [1]
runs = [2, 5, 10]
gpus = [ 1 ]
gpu_modes = [0]

buckets = [2]
vector_bytes_sizes = [2]
verify = false

# results
output = "benchmark/run/local/probe/test1"