[test]
# test data
elements = 10_000
element_max = 1000
rs_scale= [2.0]
rs_join_columns = [1]

# algorithm setup
# probe
probe_build_table_loads = [0.25, 0.5, 0.75, 1.0]
probe_build_n_per_threads = [1, 2, 4]
probe_build_threads = [128, 256, 512, 1024]
probe_prefix_n_per_threads = [1, 2, 4]
probe_prefix_threads = [128, 256, 512, 1024]
probe_extract_n_per_threads = [1, 2, 4]
probe_extract_threads = [128, 256, 512, 1024]
probe_extract_x_threads = [8, 16, 32, 64]

# launch
max_streams = 1
runs = 1
gpus = [ 1 ]

# results
output = "benchmark/probe/local/test1"