[kernel]
# test data
elements = [500, 1_000, 2_000, 5_000, 10_000, 25_000, 50_000, 75_000, 100_000]
max_values = [5_000]
skews = [0.0]
distribution = ["uniform"]
rs_scale= [1.0, 2.0, 4.0]
rs_join_columns = [1]
profile = true

#hashing
hash_elements_sizes = [0]
hash_algorithms = ["xor_hw"]
hash_threads = [256]
hashes_p_threads = [4]


# algorithm setup
# probe
probe_build_table_loads = [0.25]
probe_build_n_per_threads = [1]
probe_build_threads = [1024]
probe_extract_n_per_threads = [2]
probe_extract_threads = [256]
probe_modes = [0, 1, 2]

# launch
max_streams = [1]
runs = [5]
gpus = [ 1 ]
gpu_modes = [0]

buckets = [2]
vector_bytes_sizes = [2]
verify = false
join_modes = [0]

# results
output = "benchmark/run/remote/probe/kernel_parameters_profile"

[dist]
# test data
elements = [500, 1_000, 2_000, 5_000, 10_000, 25_000, 50_000, 75_000, 100_000]
max_values = [2_000, 5_000, 10_000, 100_000, 1_000_000]
skews = [0.0, 0.1, 0.25, 0.5, 0.75, 1.0, 2.0]
distribution = ["uniform", "zipf"]
rs_scale= [1.0, 2.0, 4.0]
rs_join_columns = [1]
profile = false


hash_elements_sizes = [0]
hash_algorithms = ["xor_hw"]
hash_threads = [256]
hashes_p_threads = [4]

# algorithm setup
# probe
probe_build_table_loads = [0.25]
probe_build_n_per_threads = [1]
probe_build_threads = [1024]
probe_extract_n_per_threads = [1]
probe_extract_threads = [128]
probe_modes = [1]

# launch
max_streams = [1]
runs = [5, 10, 20]
gpus = [ 1 ]
gpu_modes = [0]

buckets = [2]
vector_bytes_sizes = [2]
verify = false
join_modes = [0]

# results
output = "benchmark/run/remote/probe/all_dist"


[runs]
# test data
elements = [5_000]
max_values = [5_000]
skews = [0.0]
distribution = ["uniform"]
rs_scale= [1.0]
rs_join_columns = [1]
profile = false


hash_elements_sizes = [0]
hash_algorithms = ["xor_hw"]
hash_threads = [256]
hashes_p_threads = [4]

# algorithm setup
# probe
probe_build_table_loads = [0.25]
probe_build_n_per_threads = [1]
probe_build_threads = [1024]
probe_extract_n_per_threads = [1]
probe_extract_threads = [256]
probe_modes = [2]

# launch
max_streams = [1]
runs = [5, 10, 20, 30]
gpus = [ 1 ]
gpu_modes = [0]

buckets = [2]
vector_bytes_sizes = [2]
verify = false
join_modes = [0]

# results
output = "benchmark/run/remote/probe/runs"
